# Generated by Django 2.0.2 on 2020-06-08 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=280, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=280, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='p_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstDjangoApp.Topic'),
        ),
        migrations.AddField(
            model_name='access',
            name='a_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstDjangoApp.Page'),
        ),
    ]
